<a href="https://colab.research.google.com/github/JOELROJAS2022/JOELROJAS2022/blob/main/Comparar_deseq_con_Human1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  pequeno <- readLines("pequeno.txt", warn = FALSE)
  grande <- readLines("grande.txt", warn = FALSE)

 # Comparar si las palabras del archivo más pequeño están en el grande
  palabras_encontradas <- pequeno %in% grande

  # Crear un dataframe con los resultados
  resultado <- data.frame(
    Palabra = pequeno,
    Presente = ifelse(palabras_encontradas, "Sí", "No")
  )

  # Mostrar las palabras que Sí están en Human1
  palabras_presentes <- resultado[resultado$Presente == "Sí", ]
  palabras_presentes

    Palabra   Presente
2   SARDH     Sí
5   UQCR10    Sí
13  TRIM63    Sí
14  NLN       Sí
18  NAPRT     Sí
24  B4GALNT2  Sí
29  CYP46A1   Sí
31  MGAT1     Sí
33  CHST15    Sí
35  ALOX5     Sí
38  ACSBG1    Sí
39  MGAT1     Sí
42  CYP2U1    Sí
43  TRMU      Sí
48  USP48     Sí
50  ETNK2     Sí
51  CHST5     Sí
52  ALDOA     Sí
54  ITPA      Sí
56  IDH3A     Sí
57  ACOT7     Sí
58  TREX1     Sí
60  GSR       Sí
61  SUCLA2    Sí
78  TYR       Sí
80  ABHD5     Sí
81  PDP1      Sí
83  PIP4K2C   Sí
89  ART4      Sí
97  PIGB      Sí
98  C1GALT1C1 Sí
107 PLA2G4D   Sí
114 COX10     Sí
115 USP35     Sí
117 AWAT2     Sí
118 HACE1     Sí
120 MTFMT     Sí
124 ADCY1     Sí
129 DBI       Sí
134 ANAPC11   Sí
137 GK        Sí
138 MIOX      Sí
139 SLC27A5   Sí
141 GSTZ1     Sí

In [ ]:
x = read.csv("genes_con_datos_dia_3.csv", sep = ";")

y = readLines("Genes TF.txt")
y = as.data.frame(y)

genes_filtrados <- x[x$Genes %in% y$y,]

genes_filtrados

In [ ]:
install.packages("openxlsx")
library(openxlsx)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
write.xlsx(genes_filtrados , file = "genes filtrados.xlsx")

In [ ]:
palabras_encontradas <- y$y %in% x$Genes


 resultado <- data.frame(
    Palabra = y$y,
    Presente = ifelse(palabras_encontradas, "Sí", "No")
  )

  # Mostrar las palabras que Sí están en Human1
  palabras_presentes <- resultado[resultado$Presente == "No", ]
  palabras_presentes

   Palabra Presente
4  CEBPA   No
6  E2F1    No
8  EGR1    No
15 GATA3   No
18 JUN     No
29 SP1     No

In [ ]:
install.packages("readxl")
library(readxl)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
#miRNA
x = read_excel("mirna.xlsx")

y = readLines("Genes miRNA.txt")
y = as.data.frame(y)

genes_filtrados <- x[x$Gene %in% y$y,]

(genes_filtrados)

Warning message in readLines("Genes miRNA.txt"):
“incomplete final line found on 'Genes miRNA.txt'”

   Gene            baseMean     log2FoldChange lfcSE     stat
1  ENST00000362265   292.068117  1.80147684    0.6237742  2.88802720
2  ENST00000362147    34.113564  2.63134622    3.6665250  0.71766761
3  ENST00000362127    86.152760 -2.15579776    1.2823576 -1.68112055
4  ENST00000362154 17662.386747 -0.41455176    0.4938244 -0.83947195
5  ENST00000384832    45.365409 -0.09786836    1.1392464 -0.08590623
6  ENST00000362195   325.025081  0.52395595    0.6241872  0.83942117
7  ENST00000362273     1.844347 -4.33075016    3.9305646 -1.10181376
8  ENST00000384870     2.539546 -4.79384521    3.9240442 -1.22165932
9  ENST00000385201 16041.692889  1.19484221    0.4861471  2.45777918
10 ENST00000385012   440.522796 -0.26327374    0.7188345 -0.36625085
11 ENST00000385060 86140.750397  1.44321915    0.5770547  2.50100931
12 ENST00000385018    20.332502  1.67049896    2.4059430  0.69432191
13 ENST00000385128    11.602833 -1.53093195    2.7594943 -0.55478714
14 ENST00000385204  1035.404773 -1.79290911    0.5904628 -3.03644734
15 ENST00000516053     5.904709 -6.01012159    3.7269360 -1.61261732
16 ENST00000385273  5373.999888  0.56551140    0.5266282  1.07383434
17 ENST00000385259     9.199722  6.65709565    3.1969818  2.08230640
18 ENST00000408243    25.902082  0.36897483    1.6941870  0.21778873
19 ENST00000385300     2.709084 -4.88534861    3.9229845 -1.24531427
20 ENST00000385282  3085.048427 -0.04486460    0.5126112 -0.08752170
21 ENST00000591554   199.638738  0.18476582    0.7013740  0.26343409
22 ENST00000579929    25.439816  0.43977520    1.3835162  0.31786775
23 ENST00000607575   334.881436 -1.60812581    0.6632678 -2.42454974
   pvalue                padj
1  3.8766635272847001E-3 5.8842214253427998E-2
2  0.47296225605353998   0.84813906676268003
3  9.2739502180600994E-2 0.41278772135015002
4  0.40120452159860998   0.79656962292033995
5  0.93154095906296996   0.97513524039843003
6  0.40123300970450998   0.79656962292033995
7  0.27054264749709001   NA
8  0.22183648742264001   NA
9  1.3979910222415E-2    0.14146337725062999
10 0.71417790121869995   0.92235823808088002
11 1.2383992410404001E-2 0.13157991936055
12 0.48748035403536      0.8536891435749
13 0.57904026222412996   0.88205057865683001
14 2.3938392223002E-3    4.4233985629459002E-2
15 0.10682767270929      NA
16 0.28289693710398001   0.71566189445948003
17 3.7314492079189999E-2 NA
18 0.82759372590650004   0.93142501294613
19 0.21301625186873999   NA
20 0.9302568402004       0.97513524039843003
21 0.79221602151185      0.92752564502075996
22 0.75058525364685003   0.92235823808088002
23 1.5327383571769999E-2 0.14804859131823001

In [ ]:
palabras_encontradas <- y$y %in% x$Gene


 resultado <- data.frame(
    Palabra = y$y,
    Presente = ifelse(palabras_encontradas, "Sí", "No")
  )

  # Mostrar las palabras que Sí están en Human1
  palabras_presentes <- resultado[resultado$Presente == "Sí", ]
  palabras_presentes

   Palabra         Presente
1  ENST00000607575 Sí
2  ENST00000579929 Sí
3  ENST00000362273 Sí
4  ENST00000384832 Sí
5  ENST00000384832 Sí
6  ENST00000385204 Sí
7  ENST00000385012 Sí
8  ENST00000385060 Sí
9  ENST00000385201 Sí
10 ENST00000385300 Sí
11 ENST00000385282 Sí
12 ENST00000516053 Sí
13 ENST00000591554 Sí
14 ENST00000385018 Sí
15 ENST00000408243 Sí
16 ENST00000385128 Sí
17 ENST00000385273 Sí
18 ENST00000362127 Sí
19 ENST00000362127 Sí
20 ENST00000384870 Sí
21 ENST00000362154 Sí
22 ENST00000362195 Sí
23 ENST00000362265 Sí
24 ENST00000385259 Sí
25 ENST00000362147 Sí

In [ ]:
write.xlsx(genes_filtrados, file = "mirna_filtrados.xlsx")